[package]
edition = "2024"
name    = "entity"
publish = false
version = "0.1.0"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
axum-login.workspace = true
sea-orm.workspace    = true
serde.workspace      = true
utoipa.workspace     = true
